#!/bin/sh
while read file
do
  case "$1" in
  "w") 	
    wal -i "$file"
    cat ~/.cache/wal/colors.Xresources > ~/.Xresources
    pywalfox update
    killall dunst && dunst &
    killall dwm
    dwmblocks &
    pkill sxiv
    notify-send "Wallpaper and colorscheme updated!" ;;

  "y")
    xclip -selection clipboard "$file" -t image/png &&
    notify-send "$file copied to clipboard!"
  esac
done
